#!/bin/sh
#
# A quick bash script that sets up the LD_LIBRARY_PATH
# and then launches the application
#

##
# Find the bin directory
##
BIN_DIR=`dirname $0`
TMP="${BIN_DIR#?}"

if [ "${BIN_DIR%$TMP}" != "/" ]; then
  BIN_DIR=$PWD/$BIN_DIR
fi

##
# Find and export the lib directory
##
LIB_DIR="${BIN_DIR}./linux"
LD_LIBRARY_PATH=$LIB_DIR
export LD_LIBRARY_PATH


##
# Find and run the application 
##
if [ $1 = "dm" ] ; then
  $BIN_DIR/dm
elif [ $1 = "pc" ] ; then
  $BIN_DIR/pc
elif [ $1 = "table" ] ; then
  $BIN_DIR/table
elif [ $1 = "editor" ] ; then
  $BIN_DIR/tiled
elif [ $1 = "view" ] ; then
  $BIN_DIR/tmxviewer "$2"
elif [ $1 = "pipeline" ] ; then
  $BIN_DIR/pipeline
elif [ $1 = "mtv" ] ; then
  $BIN_DIR/mtv
else
  echo "-----------------------"
  echo "Error. Invalid command"
  echo "Usage: ${0} <command> <options>"
  echo "   where command is [dm | pc | table | editor | view]"
  echo "   example: ${0} gm"
  echo "   only view takes an option"
  echo "   example: ${0} view ../maps/test.tmx"
  
fi




#$BIN_DIR/$APP "$@"

